// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicColor,
  DefaultColorProps
} from "./plasmic/color_tool/PlasmicColor";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface ColorProps extends DefaultColorProps {
  color?: string;
  name?: string;
  hexCode?: string;
}

function Color_(props: ColorProps, ref: HTMLElementRefOf<"div">) {
  

  return <PlasmicColor name={props.name} hexCode={props.hexCode} style={{backgroundColor:props.color}} root={{ ref }} {...props} />;
}

const Color = React.forwardRef(Color_);
export default Color;
