// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicColorField,
  DefaultColorFieldProps
} from "./plasmic/color_tool/PlasmicColorField";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import chroma from "chroma-js";
import { ColorsContext } from "./Theme";
import { PlasmicOptionsField__ArgProps } from "./plasmic/color_tool/PlasmicOptionsField";

export interface ColorFieldProps extends DefaultColorFieldProps {}

function ColorField_(props: ColorFieldProps, ref: HTMLElementRefOf<"div">) {
  const config = React.useContext(ColorsContext)
  const [color, setColor] = React.useState(config.baseValue);


  return <PlasmicColorField input={{
    props:{
      value: chroma(color).hsl()[0].toFixed(2),
      onChange:(e) => {
        setColor(chroma.hsl(Number(e.target.value), 1, 0.5).hex());
      }
    }
  }}
    huePicker={{
    props:{
      color: color,
      onChange: (e) => {
        setColor(e.hex);
      }
    }
  }} root={{ ref }} {...props} />;
}

const ColorField = React.forwardRef(ColorField_);
export default ColorField;
