// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicField,
  DefaultFieldProps
} from "./plasmic/color_tool/PlasmicField";
import { HTMLElementRefOf } from "@plasmicapp/react-web";


export interface FieldProps extends DefaultFieldProps {
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

function Field_(props: FieldProps, ref: HTMLElementRefOf<"div">) {

  return <PlasmicField root={{ ref }} {...props} />;
}

const Field = React.forwardRef(Field_);
export default Field;
