// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicThemes,
  DefaultThemesProps
} from "./plasmic/color_tool/PlasmicThemes";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import Theme from "./Theme";

export interface ThemesProps extends DefaultThemesProps {}

function Themes_(props: ThemesProps, ref: HTMLElementRefOf<"div">) {
  const [numberOfThemes, setNumberOfThemes] = React.useState(1);
  return (
    <PlasmicThemes
      count={Array.from(Array(numberOfThemes).keys()).map((i) => {
        return <Theme key={i} />;
      })}
      add={{
        props: {
          onClick: () => {
            setNumberOfThemes(numberOfThemes + 1);
          },
        },
      }}
      root={{ ref }}
      {...props}
    />
  );
}

const Themes = React.forwardRef(Themes_);
export default Themes;
