// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dczqNaFYoArv9QmtqhGLsR
// Component: AIPmHdmqsY
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Input from "../../Input"; // plasmic-import: 434vhQcoRkn/component

import { DarkValue, useDark } from "./PlasmicGlobalVariant__Dark"; // plasmic-import: AsCuTyckBi/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: dczqNaFYoArv9QmtqhGLsR/projectcss
import sty from "./PlasmicInputField.module.css"; // plasmic-import: AIPmHdmqsY/css

export type PlasmicInputField__VariantMembers = {};

export type PlasmicInputField__VariantsArgs = {};
type VariantPropType = keyof PlasmicInputField__VariantsArgs;
export const PlasmicInputField__VariantProps = new Array<VariantPropType>();

export type PlasmicInputField__ArgsType = {
  children?: React.ReactNode;
  placeholder?: string;
  value?: any;
  type?: string;
  step?: any;
  max?: any;
  min?: any;
  maxLength?: number;
};

type ArgPropType = keyof PlasmicInputField__ArgsType;
export const PlasmicInputField__ArgProps = new Array<ArgPropType>(
  "children",
  "placeholder",
  "value",
  "type",
  "step",
  "max",
  "min",
  "maxLength"
);

export type PlasmicInputField__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  text?: p.Flex<"div">;
  input?: p.Flex<typeof Input>;
};

export interface DefaultInputFieldProps {
  children?: React.ReactNode;
  placeholder?: string;
  value?: any;
  type?: string;
  step?: any;
  max?: any;
  min?: any;
  maxLength?: number;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInputField__RenderFunc(props: {
  variants: PlasmicInputField__VariantsArgs;
  args: PlasmicInputField__ArgsType;
  overrides: PlasmicInputField__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          type: "Text" as const,
          step: "1" as const
        },
        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: true
          ? ({ $props, $state, $queries, $ctx }) => $props["value"]
          : undefined
      }
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  const globalVariants = ensureGlobalVariants({
    dark: useDark()
  });

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "baseValue",
            value: args.children,
            className: classNames(sty.slotTargetChildren, {
              [sty.slotTargetChildrenglobal_dark__true]: hasVariant(
                globalVariants,
                "dark",
                "_true"
              )
            })
          })}
        </div>

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text,
            {
              [sty.textglobal_dark__true]: hasVariant(
                globalVariants,
                "dark",
                "_true"
              )
            }
          )}
        >
          {":"}
        </div>

        <Input
          data-plasmic-name={"input"}
          data-plasmic-override={overrides.input}
          className={classNames("__wab_instance", sty.input)}
          endIcon={
            <svg
              className={classNames(projectcss.all, sty.svg__swgG5)}
              role={"img"}
            />
          }
          max={args.max}
          maxLength={args.maxLength}
          min={args.min}
          onChange={(...eventArgs) => {
            p.generateStateOnChangeProp($state, ["input", "value"])(
              (e => e.target?.value).apply(null, eventArgs)
            );
          }}
          placeholder={args.placeholder}
          startIcon={
            <svg
              className={classNames(projectcss.all, sty.svg___0OeO)}
              role={"img"}
            />
          }
          step={args.step}
          type={args.type}
          value={p.generateStateValueProp($state, ["input", "value"])}
        />
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "text", "input"],
  freeBox: ["freeBox"],
  text: ["text"],
  input: ["input"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  text: "div";
  input: typeof Input;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInputField__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInputField__VariantsArgs;
    args?: PlasmicInputField__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicInputField__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicInputField__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicInputField__ArgProps,
          internalVariantPropNames: PlasmicInputField__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicInputField__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInputField";
  } else {
    func.displayName = `PlasmicInputField.${nodeName}`;
  }
  return func;
}

export const PlasmicInputField = Object.assign(
  // Top-level PlasmicInputField renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    text: makeNodeComponent("text"),
    input: makeNodeComponent("input"),

    // Metadata about props expected for PlasmicInputField
    internalVariantProps: PlasmicInputField__VariantProps,
    internalArgProps: PlasmicInputField__ArgProps
  }
);

export default PlasmicInputField;
/* prettier-ignore-end */
